# Identificadores del proyecto
sonar.projectKey=com.universidad:productos-service
sonar.projectName=Productos Service
sonar.projectVersion=1.0

# Rutas de código y pruebas
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Integración con JaCoCo para cobertura
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones (archivos que no se deben analizar)
sonar.exclusions=**/*Application.java

# Conexión al servidor local
sonar.host.url=http://localhost:9000
sonar.qualitygate.wait=false
sonar.token=sqp_65463ccff03acabcfd33479fcbacaf9d90d0412b