# Identificadores del proyecto
sonar.projectKey=com.universidad:productos-service2
sonar.projectName=Productos Service2
sonar.projectVersion=1.0

# Rutas de código y pruebas
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Integración con JaCoCo para cobertura
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones (archivos que no se deben analizar)
sonar.exclusions=**/*Application.java

# Conexión al servidor local
sonar.host.url=http://localhost:9000
sonar.qualitygate.wait=false
sonar.token=sqp_e943d5e7591940588e6aabb55d4195c8cc399c1a